version: "3.3"

services:
  db:
      container_name: db_delivery
      image: mysql:8.0.30
      restart: always
      ports:
        - 3310:3306
      environment:
        MYSQL_ROOT_PASSWORD: password

